### ISSUE TITLE
[Question] How do we aggregate multiple 'results.json' to plot?

### ISSUE THREAD

**Issue by HideakiImamura** [sile/kurobako#10]
Hi, now, I want to aggregate multiple `results.json` files to plot.
In my case, I have three files; `results.json`, `results2.json`, and `results3.json`. And I will extract some lines from each `results*.json` file. Then, I will aggregate those lines to produce the new plot. Is there any options to aggregate multiple sources for `kurobako plot` command?

**Comment by sile** [comment]
Hi,
You can aggregate the result files by simply concatenating the file contents, e.g., `cat *.json | kurobako plot`.

**Comment by HideakiImamura** [comment]
Thank you for your reply. I can concatenate multiple files as you suggested.
