### ISSUE TITLE
[Question] How do I fix the plot of the `kurobako plot curve` command?

### ISSUE THREAD

**Issue by HideakiImamura** [sile/kurobako#7]
I executed the series of commands in the https://tech.preferred.jp/ja/blog/kurobako/. I was able to run the last command `kurobako plot curve` without errors, but got the following plot. It looks like strings are skewed.
Now, I think my image drawing library (gnuplot) has some troubles. My installation of gnuplot is done by `brew`.

![hpo-bench-parkinson-f0d3607d18e1b6cb254b3ecaae6027e729561599ff8d3a45bd5112103f173b90](https://user-images.githubusercontent.com/38826298/79406533-54282c00-7fd2-11ea-97e7-781347db26cb.png)

**Comment by c-bata** [comment]
Dockerfile in the following directory might help you.
https://github.com/CyberAgent/cmaes/tree/master/benchmark

**Comment by HideakiImamura** [comment]
Thank you for kind suggestion. I will check it!

**Comment by sile** [comment]
@c-bata Thanks!

@HideakiImamura Though I don't know how to solve your problem (skewed strings), I would try reproducing the result if you could tell me your Gnuplot version.

**Comment by HideakiImamura** [comment]
I'm really sorry to bother you when you're busy. My gnuplot version is the following.
```
hideakibookpuro:~ mamu$ gnuplot --version
gnuplot 5.2 patchlevel 8
```

**Comment by sile** [comment]
@HideakiImamura Thank you for the information. The gnuplot version of my environment is "gnuplot 5.2 patchlevel 6", so I think the gnuplot itself isn't the cause of your problem. The font or graphical library used by gnuplot might be wrong, but I'm not sure...
Instead, I pushed a docker image that can be used to generate images as follows:
```console
$ cat ${your result JSON file path} | docker run -v /tmp/images/:/images/ --rm -i kurobako:0.1.9 plot curve
```
Could you try the above command on your environment?

**Comment by HideakiImamura** [comment]
@sile Thank you for your kind reply. I executed the suggested command, but faced the following error. It seems that I have no right to access the docker image.
```
(venv) hideakibookpuro:fcnet_tabular_benchmarks mamu$ cat result.json | docker run -v /tmp/images/:/images/ --rm -i kurobako:0.1.9 plot curve
Unable to find image 'kurobako:0.1.9' locally
docker: Error response from daemon: pull access denied for kurobako, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
(venv) hideakibookpuro:fcnet_tabular_benchmarks mamu$ docker login
Authenticating with existing credentials...
Login Succeeded
(venv) hideakibookpuro:fcnet_tabular_benchmarks mamu$ cat result.json | docker run -v /tmp/images/:/images/ --rm -i kurobako:0.1.9 plot curve
Unable to find image 'kurobako:0.1.9' locally
docker: Error response from daemon: pull access denied for kurobako, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

**Comment by sile** [comment]
@HideakiImamura Sorry, there was a typo in the above command. You need to replace `kurobako:0.1.9` with `sile/kurobako:0.1.9` :bow:

**Comment by HideakiImamura** [comment]
@sile Thank you for your correction. If I replaced `kurobako:0.1.9` with `sile/kurobako:0.1.9`, there was no error and got the appropriate figure as follows.
![hpo-bench-protein-7c7efb839ee527be71868fc0efe0560b367cb0cb23991e0c819062ab7d9285f9](https://user-images.githubusercontent.com/38826298/79548127-e82bed80-80cf-11ea-8593-2e7773d714ca.png)
Thank you for your great help. But the figure is produced in the directory `/tmp/images`. How can I produce the figure in the current working directory? I thought that I should specify `-w` option of `docker run` command with the absolute path of the working directory, but there is no produced image.

**Comment by sile** [comment]
> How can I produce the figure in the current working directory? 

You can change the directory by modifying the `-v` argument. For example, if you specify `-v $PWD/images/:/images/`, the figures will be generated in `./images/curve/` directory.
(The `-w` option isn't relevant in this case)

**Comment by HideakiImamura** [comment]
Thank you for your great help. I got the produced images in the current directory! Thank you so much!
